### ISSUE TITLE
[Feature Request] Scaled rank requirements depending on prestige

### ISSUE THREAD

**Issue by TheosisOfficial** [okx-code/Rankup3#70]
On my server I would like to make it so that ranking up is more difficult each time you prestige. I think having a feature whereby you can set separate requirements for rankups depending on what prestige the player currently is would be cool. I hope that this isn't too out of scope for the plugin, and doesn't require too much work!

**Comment by okx-code** [comment]
This is already a feature, format your requirements like so:
```yaml
myrankup:
  rank: 'somerank'
  next: 'nextrank'
  requirements:
    default: # used when there is no prestige
    - 'money 1000'
    p1: # used in p1
    - 'money 2000'
```
etc
